"""updated models

Revision ID: ee333b79256d
Revises: 
Create Date: 2025-07-04 18:37:12.739633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee333b79256d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_assigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_assigns_account_id'), 'subject_assigns', ['account_id'], unique=False)
    op.create_index(op.f('ix_subject_assigns_id'), 'subject_assigns', ['id'], unique=False)
    op.create_index(op.f('ix_subject_assigns_subject_id'), 'subject_assigns', ['subject_id'], unique=False)
    op.create_table('exam_assigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_assigns_account_id'), 'exam_assigns', ['account_id'], unique=False)
    op.create_index(op.f('ix_exam_assigns_exam_id'), 'exam_assigns', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_assigns_id'), 'exam_assigns', ['id'], unique=False)
    op.add_column('exams', sa.Column('valid_from', sa.DateTime(), nullable=False))
    op.add_column('exams', sa.Column('valid_to', sa.DateTime(), nullable=False))
    op.alter_column('exams', 'is_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'is_active',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('exams', 'valid_to')
    op.drop_column('exams', 'valid_from')
    op.drop_index(op.f('ix_exam_assigns_id'), table_name='exam_assigns')
    op.drop_index(op.f('ix_exam_assigns_exam_id'), table_name='exam_assigns')
    op.drop_index(op.f('ix_exam_assigns_account_id'), table_name='exam_assigns')
    op.drop_table('exam_assigns')
    op.drop_index(op.f('ix_subject_assigns_subject_id'), table_name='subject_assigns')
    op.drop_index(op.f('ix_subject_assigns_id'), table_name='subject_assigns')
    op.drop_index(op.f('ix_subject_assigns_account_id'), table_name='subject_assigns')
    op.drop_table('subject_assigns')
    # ### end Alembic commands ###
